# Generated by Django 5.0.3 on 2024-05-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplements_images/')),
                ('code', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('available', models.BooleanField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('PR', 'Proteins'), ('VI', 'Vitamins'), ('CR', 'Creatines'), ('AA', 'Amino Acids'), ('PW', 'Pre-Workout')], max_length=3)),
            ],
        ),
    ]
