# Generated by Django 5.0.3 on 2024-05-31 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_description', models.TextField()),
                ('date', models.DateField()),
                ('realeastate', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='oglas_images/')),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('ФИКСНА', 'Цената е фиксна'), ('ПРЕДЛОЗИ', 'Прифаќам предлози'), ('НЕ ФИКСНА', 'Цената не е фиксна')], max_length=50)),
                ('new_user', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oglas_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
