# Generated by Django 5.0.7 on 2025-05-15 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IzdavackaKukja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('zemja', models.CharField(max_length=50)),
                ('grad', models.CharField(max_length=50)),
                ('god_osnovanje', models.DateField()),
                ('vebsajt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kniga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=50)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='sliki')),
                ('isbn', models.CharField(max_length=50)),
                ('god_izdavanje', models.DateField()),
                ('broj_strani', models.IntegerField()),
                ('dimenzii', models.IntegerField()),
                ('tip_korica', models.CharField(choices=[('M', 'Meka'), ('T', 'Tvrda')], max_length=50)),
                ('tip_kategorija', models.CharField(choices=[('R', 'Romansa'), ('T', 'Triler'), ('B', 'Biografija'), ('K', 'Klasik'), ('D', 'Drama'), ('I', 'Istorija')], max_length=50)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('izdavacka_kukja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_app.izdavackakukja')),
                ('kreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
