# Generated by Django 5.0.7 on 2025-05-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kniga',
            name='kreator',
        ),
    ]
