# Generated by Django 5.0.7 on 2025-03-27 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=50)),
                ('tel_broj', models.CharField(max_length=50)),
                ('mejl_adresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_dzvezdi', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50)),
                ('komentar', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('datum_ragjanje', models.DateField(blank=True, null=True)),
                ('broj_pasos', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TuristickiPaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=50)),
                ('destinacija', models.CharField(max_length=50)),
                ('vremetraenje_denovi', models.IntegerField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum_poagjanje', models.DateField(blank=True, null=True)),
                ('broj_slobodni_mesta', models.IntegerField()),
                ('turist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01_app.turist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agencija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('sopstvenik', models.CharField(max_length=50)),
                ('datum_osnovanje', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kontakt_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01_app.kontaktinfo')),
                ('turisticki_paketi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01_app.turistickipaket')),
            ],
        ),
        migrations.CreateModel(
            name='TuristickiPaketOcena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01_app.ocena')),
                ('turisticki_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01_app.turistickipaket')),
            ],
        ),
        migrations.CreateModel(
            name='TuristickiPaketTurist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(blank=True, null=True)),
                ('turist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01_app.turist')),
                ('turisticki_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01_app.turistickipaket')),
            ],
        ),
    ]
