# Generated by Django 5.0.3 on 2024-05-27 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('country', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=50)),
                ('max_speed', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Autoservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_founded', models.IntegerField()),
                ('services_oldtimers', models.BooleanField()),
                ('specialized_manufacturers', models.ManyToManyField(related_name='specialized_services', to='car_app.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('registered_date', models.DateField()),
                ('problem_desc', models.TextField()),
                ('problem_image', models.ImageField(blank=True, null=True, upload_to='cars_images/')),
                ('auto_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.autoservice')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
