# Generated by Django 5.0.3 on 2024-05-30 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_of_establishment', models.IntegerField()),
                ('Flight_out_Europe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balloon_type', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('max_passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_of_birth', models.IntegerField()),
                ('flying_hours', models.IntegerField()),
                ('act', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('start_airport_name', models.CharField(max_length=50)),
                ('end_airport_name', models.CharField(max_length=50)),
                ('flight_image', models.ImageField(blank=True, null=True, upload_to='flight_images/')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloon_app.airline')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloon_app.balloon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloon_app.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='PilotAirline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloon_app.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloon_app.pilot')),
            ],
        ),
    ]
