# Generated by Django 4.2.21 on 2025-05-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cake_shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cake",
            name="baker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cake_shop_app.baker",
            ),
        ),
    ]
