# Generated by Django 4.2.21 on 2025-05-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cake_shop_app", "0002_cake_baker"),
    ]

    operations = [
        migrations.AddField(
            model_name="baker",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="bakers/"),
        ),
        migrations.AlterField(
            model_name="cake",
            name="baker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cakes",
                to="cake_shop_app.baker",
            ),
        ),
    ]
